name: Deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [main]

jobs:
  deploy_lambda:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Assume DEV Role
        uses: youyo/awscredswrap@master
        with:
          role_arn: arn:aws:iam::192461108232:role/SDC-Vxgateway
          duration_seconds: 1200
          role_session_name: dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-central-1'
      - name: npm install
        env:
          CI: true
        run: |
          npm ci
      - name: run unit tests       
        run: |
          npm run
      - name: build
        run: |
          npx ncc build src/index.ts -o dist/lambda
          cp swagger.yaml dist/lambda/swagger.yaml
      - name: Deploy to S3
        run: aws s3 sync ./dist/lambda s3://dev-vxgateway-lambdas/
      - name: update lambda
        run: |
          aws lambda update-function-code --function-name=pa-lambda-koa-webserver --s3-bucket=dev-vxgateway-lambdas     
