name: Deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [main]

jobs:
  deploy_lambda:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: npm install
        env:
          CI: true
        run: |
          npm ci
      - name: run unit tests       
        run: |
          npm run
      - name: build
        run: |
          npx ncc build src/index.ts -o dist/lambda
          cp swagger.yaml dist/lambda/swagger.yaml
      - name: update lambda
        run: |
          aws lambda update-function-code --function-name=pa-lambda-koa-webserver --s3-bucket=lambdas     
